@startuml catering_cooks
skinparam actorStyle Hollow 
skinparam usecase {
BackgroundColor DarkSeaGreen
BorderColor DarkSlateGray

BackgroundColor<< Main >> YellowGreen 
BorderColor<< Main >> YellowGreen 

ArrowColor tan 
ActorBorderColor black
ActorFontName Courier

ActorBackgroundColor<< Human >> Black
}
left to right direction
actor Cook
rectangle CalorieTracker {
  (Login)
  (Register)
  (View Saved Diet from Professionals)
  (View Main Menu Where Foods Can be Added to Daily Intake)
  (View and Add Foods to Tracker by Search Criteria)
  (View Daily Food Intake)
  (View Total Daily Calories)
  (View Total Daily Protein)
  (View Total Daily Carbohydrates)
  (View Total Daily Fats)
  (Exit Back to Main Menu)
  (Save Diet)
  (Logout)
}
Cook --> (Login)
Cook --> (Register)
Cook --> (View Saved Diet from Professionals) : As a Cook, "professionals" refers to Guests, the Hosts that you are cooking for, etc.
Cook --> (View Main Menu Where Foods Can be Added to Daily Intake)
Cook --> (View and Add Foods to Tracker by Search Criteria) : In case guests have certain requirements or allergies
Cook --> (Exit Back to Main Menu)
Cook --> (Logout)
@enduml