@startuml doctor
skinparam actorStyle Hollow 
skinparam usecase {
BackgroundColor DarkSeaGreen
BorderColor DarkSlateGray

BackgroundColor<< Main >> YellowGreen 
BorderColor<< Main >> YellowGreen 

ArrowColor tan 
ActorBorderColor black
ActorFontName Courier

ActorBackgroundColor<< Human >> Black
}
left to right direction
actor Doctor
rectangle CalorieTracker {
  (Login)
  (Register)
  (View Saved Diet from Professionals)
  (View Main Menu Where Foods Can be Added to Daily Intake)
  (View and Add Foods to Tracker by Search Criteria)
  (View Daily Food Intake)
  (View Total Daily Calories)
  (View Total Daily Protein)
  (View Total Daily Carbohydrates)
  (View Total Daily Fats)
  (Exit Back to Main Menu)
  (Save Diet)
  (Logout)
}
Doctor --> (View Main Menu Where Foods Can be Added to Daily Intake) : The doctor would use this to add their patients' foods and see what macronutrient is either lacking or excessive 
Doctor --> (View and Add Foods to Tracker by Search Criteria) : In case the patient has special diet requirements, this would save lots of time
Doctor --> (View Daily Food Intake)
Doctor --> (View Total Daily Calories)
Doctor --> (View Total Daily Protein)
Doctor --> (View Total Daily Carbohydrates)
Doctor --> (View Total Daily Fats)
Doctor --> (Exit Back to Main Menu)
@enduml