@startuml patient
skinparam actorStyle Hollow 
skinparam usecase {
BackgroundColor DarkSeaGreen
BorderColor DarkSlateGray

BackgroundColor<< Main >> YellowGreen 
BorderColor<< Main >> YellowGreen 

ArrowColor tan 
ActorBorderColor black
ActorFontName Courier

ActorBackgroundColor<< Human >> Black
}
left to right direction
actor Patient
rectangle CalorieTracker {
  (Login)
  (Register)
  (View Saved Diet from Professionals)
  (View Main Menu Where Foods Can be Added to Daily Intake)
  (View and Add Foods to Tracker by Search Criteria)
  (View Daily Food Intake)
  (View Total Daily Calories)
  (View Total Daily Protein)
  (View Total Daily Carbohydrates)
  (View Total Daily Fats)
  (Exit Back to Main Menu)
  (Save Diet)
  (Logout)
}
Patient --> (Login)
Patient --> (Register)
Patient --> (View Saved Diet from Professionals) : As a patient, "professionals" refers to Doctors, Nurses, etc.
Patient --> (View Main Menu Where Foods Can be Added to Daily Intake)
Patient --> (View and Add Foods to Tracker by Search Criteria) : Allergens, Vegetarian, etc.
Patient --> (View Daily Food Intake)
Patient --> (View Total Daily Calories)
Patient --> (View Total Daily Protein)
Patient --> (View Total Daily Carbohydrates)
Patient --> (View Total Daily Fats)
Patient --> (Exit Back to Main Menu)
Patient --> (Save Diet)
Patient --> (Logout)
@enduml