@startuml users
skinparam actorStyle Hollow 
skinparam usecase {
BackgroundColor DarkSeaGreen
BorderColor DarkSlateGray

BackgroundColor<< Main >> YellowGreen 
BorderColor<< Main >> YellowGreen 

ArrowColor tan 
ActorBorderColor black
ActorFontName Courier

ActorBackgroundColor<< Human >> Black
}
left to right direction
actor Users
rectangle CalorieTracker {
  (Login)
  (Register)
  (View Saved Diet from Professionals)
  (View Main Menu Where Foods Can be Added to Daily Intake)
  (View and Add Foods to Tracker by Search Criteria)
  (View Daily Food Intake)
  (View Total Daily Calories)
  (View Total Daily Protein)
  (View Total Daily Carbohydrates)
  (View Total Daily Fats)
  (Exit Back to Main Menu)
  (Save Diet)
  (Logout)
}
Users --> (Login)
Users --> (Register)
Users --> (View Main Menu Where Foods Can be Added to Daily Intake)
Users --> (View and Add Foods to Tracker by Search Criteria) : In case users have special diet requirements
Users --> (View Daily Food Intake)
Users -->  (View Total Daily Calories)
Users --> (View Total Daily Protein)
Users --> (View Total Daily Carbohydrates)
Users --> (View Total Daily Fats)
Users --> (Exit Back to Main Menu)
Users --> (Save Diet) : If a user really enjoyed a lot of their meals on a specific day, there a able to save all that they ate in order to refer back to it in the future
Users --> (Logout)
@enduml