@startuml users
skinparam actorStyle Hollow 
skinparam usecase {
BackgroundColor DarkSeaGreen
BorderColor DarkSlateGray

BackgroundColor<< Main >> YellowGreen 
BorderColor<< Main >> YellowGreen 

ArrowColor tan 
ActorBorderColor black
ActorFontName Courier

ActorBackgroundColor<< Human >> Black
}
left to right direction
actor Users
rectangle CalorieTracker {
  (Login)
  (Register)
  (View Saved Diet from Professionals)
  (View Main Menu Where Foods Can be Added to Daily Intake)
  (View and Add Foods to Tracker by Search Criteria)
  (View Daily Food Intake)
  (Add New Item to Daily Intake)
  (Empty Daily Intake)
  (Remove Item from Daily Intake)
  (Update Item Quantity in Daily Intake)
  (Exit Back to Main Menu)
  (Save Diet)
  (Send Diet)
  (Logout)
}
Users --> (Login)
Users --> (Register)
Users --> (View Saved Diet from Professionals) : Professionals may refer to Doctors, Personal Trainers, Nutrionists, etc.
Users --> (View Main Menu Where Foods Can be Added to Daily Intake)
Users --> (View and Add Foods to Tracker by Search Criteria) : In case of allergies, diseases, diet choices, etc.
Users --> (View Daily Food Intake) : All foods consumed that day will be able to be viewed here including all macronutrients
Users --> (Add New Item to Daily Intake)
Users --> (Empty Daily Intake) : Empty it so you can start fresh the next day
Users --> (Remove Item from Daily Intake) : In case of misclicks or something of the sort
Users --> (Update Item Quantity in Daily Intake)
Users --> (Exit Back to Main Menu)
Users --> (Save Diet) : If one really enjoyed what they ate that day, they may save it for future reference
Users --> (Logout)
@enduml