@startuml register
actor "Register User"
boundary "System" as system
control "Databse" as database
control "Authentication" as auth
Customer -> system: Register
activate system
system -> auth: hash_password(password)
activate auth
auth --> system: Password Tuple
deactivate auth
system -> database: db.insert_user(username, key, email, first_name, last_name)
activate database
database --> system: None
deactivate database
system -> system: redirect to home page
deactivate system
@enduml